export const ExceptionCodes = {
  AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  AUTH_EMAIL_TAKEN: 'AUTH_EMAIL_TAKEN',
  AUTH_UNAUTHORIZED: 'AUTH_UNAUTHORIZED',

  COMPANY_NOT_FOUND: 'COMPANY_NOT_FOUND',
  COMPANY_REQUIRED: 'COMPANY_REQUIRED',
  COMPANY_INVALID_MAGIC_LINK: 'COMPANY_INVALID_MAGIC_LINK',
  COMPANY_ALREADY_ASSIGNED: 'COMPANY_ALREADY_ASSIGNED',

  REPORT_NOT_FOUND: 'REPORT_NOT_FOUND',

  RESOURCE_ALREADY_EXISTS: 'RESOURCE_ALREADY_EXISTS',
  RESOURCE_NOT_FOUND: 'RESOURCE_NOT_FOUND',
  INVALID_REFERENCE: 'INVALID_REFERENCE',

  VALIDATION_ERROR: 'VALIDATION_ERROR',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
} as const;

export type ExceptionCode =
  (typeof ExceptionCodes)[keyof typeof ExceptionCodes];
