[build]
builder = "nixpacks"

[variables]
NIXPACKS_NODE_VERSION = "23"

[deploy]
startCommand = "cd apps/api && yarn prisma migrate deploy && node dist/main"
healthcheckPath = "/api"
healthcheckTimeout = 10
restartPolicyType = "on_failure"

[[services]]
name = "api"
